name: Github Page Deploys on server
'on':
  push:
    branches:
      - development
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 15.x
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run the tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
      - name: Server setup
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: hahewoto.ssh.cloud.hostpoint.ch
          port: 22
          username: hahewoto
          key: ${{ secrets.BF_PRIVATE_KEY }}
          script: |
            cd /www/react-test/
            git pull origin gh-pages
            git status

