# This is a basic workflow to help you get started with Actions

name: Github Page Deploys

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      
      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.

			- name: Server setup
      uses: appleboy/ssh-action@v0.1.4
			with:
				# ssh host
				host: 192.168.2.230
				# ssh port
				port: 22
				# ssh key passphrase
				username: ubuntu
				key: ${{ secret.PRIVATE_KEY }}
				script: |
					cd /var/www/html/react-sample/
					git pull origin gh-pages
					git status
